import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import { VStack } from "@chakra-ui/react";
import DataTable from "@/components/Table";
import { Supplies, DataTableColumn } from "@/types";
import { fetchData } from "@/utils/client";
import {
  cleanData,
  cleanTableCols,
  generateColsFromData,
} from "@/utils/cleanCols";

const inter = Inter({ subsets: ["latin"] });

type HomeProps = {
  upcomingOrders: Supplies[];
  outgoingSupplies: Supplies[];
};

const Home: NextPage<HomeProps> = ({ upcomingOrders, outgoingSupplies }) => {
  const outgoingCols: DataTableColumn[] = generateColsFromData<Supplies>(
    outgoingSupplies[0] || {}
  );

  const upcomingCols: DataTableColumn[] = generateColsFromData<Supplies>(
    upcomingOrders[0] || {}
  );

  return (
    <div>
      <Head>
        <title>Supply Chain Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack spacing={5}>
        <DataTable
          title="Upcoming Orders"
          cols={cleanTableCols(upcomingCols)}
          items={cleanData(upcomingOrders)}
        />
        <DataTable
          title="Outgoing Supplies"
          cols={cleanTableCols(outgoingCols)}
          items={cleanData(outgoingSupplies)}
        />
      </VStack>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  // get inbound supplies, not yet received, shipped
  const orders = await fetchData<Supplies>("events");

  const upcomingOrders = orders.filter(
    (order) => order.status === "Shipped" || order.movement === "Inbound"
  );

  const outgoingSupplies = orders.filter(
    (order) => order.status === "Shipped" || order.movement === "Outbound"
  );

  return {
    props: {
      upcomingOrders,
      outgoingSupplies,
    },
  };
}
